import turtle as t

x=-150
t.screensize(100,2000)
t.pensize(5)

t.speed(5)

smod="n"
def gotos(a,b):
    if smod=="y"or"":
        t.pensize(1)
        t.pendown()
        t.goto(a,b)
        t.pensize(5)
    else:
        t.penup()
        t.goto(a,b)
        t.pendown()

def drawer(characterVariables):
    if characterVariables=="A":
        t.lt(80)
        t.fd(100)
        t.rt(150)
        t.fd(110)
        t.bk(55)
        t.rt(110)
        t.fd(26)

        # t.penup()
        # t.bk(100)
    elif characterVariables=="B":
        t.left(90)
        t.fd(100)
        t.bk(50)
        t.rt(90)
        t.circle(25,180)
        t.left(90)
        t.fd(50)
        t.left(90)
        t.circle(-25,180)
        t.rt(180)
    elif characterVariables=="C":
        t.circle(50,60)
        t.penup()
        t.circle(50,60)
        t.pendown()
        t.circle(50,240)
    elif characterVariables=="D":
        t.lt(90)
        t.fd(100)
        t.bk(100)
        t.rt(90)
        t.circle(50,180)
    elif characterVariables=="E":
        gotos(x,100)
        t.fd(50)
        gotos(x,50)
        t.fd(50)
        gotos(x,100)
        t.rt(90)
        t.fd(100)
        t.lt(90)
        t.fd(50)
        
    elif characterVariables=="F":
        t.lt(90)
        t.fd(100)
        t.rt(90)
        t.fd(50)
        t.bk(50)
        t.lt(90)
        t.bk(50)
        t.rt(90)
        t.fd(50)
    elif characterVariables=="G":
        t.penup()
        gotos(x,100)
        t.pendown()
        t.lt(180)
        t.circle(50,180)
        t.lt(90)
        t.fd(50)
    elif characterVariables=="H":
        t.lt(90)
        t.fd(100)
        t.bk(50)
        t.rt(90)
        t.fd(50)
        t.lt(90)
        t.fd(50)
        t.bk(100)
    elif characterVariables=="I":
        t.fd(50)
        t.bk(25)
        t.lt(90)
        t.fd(100)
        t.rt(90)
        t.fd(25)
        t.bk(50)
    elif characterVariables=="J":
        t.penup()
        t.fd(50)
        t.rt(90)
        t.pendown()
        t.circle(25,180)
        t.fd(100)
        t.rt(90)
        t.bk(50)
        t.fd(100)
    elif characterVariables=="K":
        t.lt(90)
        t.fd(100)
        t.bk(50)
        t.rt(45)
        t.fd(70)
        t.bk(70)
        t.rt(90)
        t.fd(70)
    elif characterVariables=="L":
        gotos(x,100)
        t.rt(90)
        t.fd(100)
        t.lt(90)
        t.fd(50)
    elif characterVariables=="M":
        t.lt(83)
        t.fd(100)
        t.rt(166)
        t.fd(100)
        t.lt(76)
        t.lt(83)
        t.fd(100)
        t.rt(166)
        t.fd(100)
        t.lt(76)
    elif characterVariables=="N":
        t.lt(90)
        t.fd(100)
        t.rt(135)
        t.fd(1)
        t.lt(135)
        t.fd(100)
    elif characterVariables=="O":
        t.penup()
        t.fd(50)
        t.pendown()
        t.circle(50)
    elif characterVariables=="P":
        t.lt(90)
        t.fd(100)
        t.bk(50)
        t.rt(90)
        t.circle(25,180)
    elif characterVariables=="Q":
        t.circle(50)
        t.circle(50,45)
        t.setheading(-45)
        t.bk(20)
        t.fd(40)
    elif characterVariables=="R":
        t.lt(90)
        t.fd(100)
        t.bk(50)
        t.rt(90)
        t.circle(25,180)
        t.lt(90)
        t.fd(50)
        t.setheading(-45)
        t.fd(75)
    elif characterVariables=="S":
        # t.penup()
        # gotos(x,75)
        # t.pendown()
        t.circle(25,180)
        t.circle(-25,180)
    elif characterVariables=="T":
        t.penup()
        t.fd(25)
        t.lt(90)
        t.pendown()
        t.fd(100)
        t.rt(90)
        t.bk(25)
        t.fd(50)
    elif characterVariables=="U":
        t.penup()
        gotos(x,100)
        t.rt(90)
        t.pendown()
        t.fd(50)
        t.circle(25,180)
        t.fd(50)
    elif characterVariables=="V":
        # t.penup()
        gotos(x,100)
        t.rt(80)
        # t.pendown()
        t.fd(100)
        t.lt(150)
        t.fd(100)
    elif characterVariables=="W":
        t.penup()
        gotos(x,100)
        t.pendown()
        t.rt(83)
        t.fd(100)
        t.lt(166)
        t.fd(100)
        t.rt(76)
        t.rt(83)
        t.fd(100)
        t.lt(166)
        t.fd(100)
        #t.lt(76)
    elif characterVariables=="X":
        t.penup()
        gotos(x,100)
        t.pendown()
        t.rt(70)
        t.fd(150)
        t.penup()
        gotos(x+50,100)
        t.pendown()
        t.rt(40)
        t.fd(150)
    elif characterVariables=="Y":
        # t.penup()
        gotos(x,100)
        # t.pendown()
        t.rt(50)
        t.fd(75)
        t.penup()
        gotos(x+50,100)
        t.pendown()
        t.rt(40)
        t.fd(60)
        t.setheading(-90)
        t.fd(50)
    elif characterVariables=="Z":
        t.penup()
        gotos(x,100)
        t.pendown()
        t.fd(50)
        t.lt(135)
        t.fd(75)
        t.setheading(0)
        t.fd(50)
    elif characterVariables==" ":
        t.penup()
        t.fd(30)
        t.pendown()

#n=input()
n=input()
t.penup()
gotos(x,0)
t.pendown()
for i in range(len(n)):
    drawer(n[i])
    x+=60
    if n[i]=="O":
        x+=50
    t.penup()
    gotos(x,0)
    t.pendown()
    t.setheading(0)
input()